version: '3.4'

services:
  deserialization.api:
    image: deserializationapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_deserialization.api$
    volumes:
      - C:\Users\Riiecco\Desktop\dotnet-training\Deserialization.API\Deserialization.API:/app
      - C:\Users\Riiecco\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_deserialization.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_deserialization.api$ bin/Debug/netcoreapp2.0/Deserialization.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
